<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Build">
    <PackageVersion Include="MinVer" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Label="Benchmarks">
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup Label="Test">
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
